name: AlwaysSpawn
authors: [Philip Shilling]
version: 2.2.3-dev1
api: [3.0.0-ALPHA7]
main: philipshilling\alwaysspawn\Loader
load: STARTUP
description: "Force your users to spawn every time they login!"